---
- name: Configuring RabbitMQ parameters
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
    owner: root
    group: rabbitmq
    mode: 0644
  become: true
  notify:
    - Restart RabbitMQ service

- name: Installing plugins for RabbitMQ
  command: rabbitmq-plugins enable {{ item }}
  changed_when: false
  become: true
  with_items:
    - "{{ rabbitmq_plugins }}"
