---
- name: Configuring erlang cookie for RabbitMQ nodes
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  become: true
  notify:
    - Restart RabbitMQ service

- name: Stopping RabbitMQ application on follower nodes
  command: rabbitmqctl stop_app
  become: true
  changed_when: false
  when: >
    node_type == "follower"

- name: Setting up the fact for master node
  set_fact:
    rabbitmq_master_node: "{{ inventory_hostname }}"
  when: >
    node_type == "master"

- name: Joining RabbitMQ master node for cluster
  command: >-
    rabbitmqctl join_cluster rabbit@{{ rabbitmq_master_node }}
  changed_when: false
  become: true
  when: >
    node_type == "follower"

- name: Starting RabbitMQ application on follower nodes
  command: >-
    rabbitmqctl start_app
  changed_when: false
  become: true
  when: >
    node_type == "follower"
