---
- name: Checking firewall service is active or not
  service_facts:
  register: service_status

- name: Getting status of firewalld service
  set_fact:
    firewall_status: service_status.ansible_facts.services["firewalld.service"].state
  when: >
    service_status.ansible_facts.services["firewalld.service"] is defined

- name: Setting fact for firwall service status
  set_fact:
    firewall_status: unknown
  when: >
    service_status.ansible_facts.services["firewalld.service"] is not defined  
  
- name: Configuring RabbitMQ ports in firewall
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items:
    - 15672
    - 5672
    - 4369
    - 25672
    - 15692
  become: true
  when: >
    firewall_status == "running"
