---
# tasks file for osm_rabbitmq
- name: Including playbook for pre-checks for RabbitMQ
  include_tasks: pre-checks.yaml

- name: Including playbook for RabbitMQ OS configurations
  include_tasks: pre-requisites.yaml

- name: Including tasks to install RabbitMQ on ub ubuntu
  include_tasks: Install-ubuntu.yaml
  when: ansible_os_family == "Debian"

- name: Including playbook to configure RabbitMQ
  include_tasks: configure.yaml

- name: Including playbook to configure firewall
  include_tasks: configure-firewall.yaml

- name: Running all handlers for RabbitMQ nodes
  meta: flush_handlers

- name: Including tasks to create RabbitMQ cluster
  include_tasks: configure-cluster.yaml
  when: create_cluster

- name: Including playbook for RabbitMQ nodes healthcheck
  include_tasks: healthcheck.yaml
