---
- name: Configuring the RabbitMQ DNS in /etc/hosts
  blockinfile:
    block: |
      {{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  become: true
  with_items:
    - "{{ groups['rabbitmq'] }}"
