---
- name: Checking rabbitmq hosts are defined or not
  fail:
    msg: "Playbook execution failed due to missing or empty required group 'rabbitmq'"
  when: groups['rabbitmq'] is not defined or groups['rabbitmq'] | length == 0

- name: Checking OS compatiblity
  fail:
    msg: >
      This role is supported with RedHat family for now.
      Debian support is under construction
  when:
    ansible_os_family != "RedHat"
