---
# handlers file for osm_rabbitmq
- name: Enable RabbitMQ service
  systemd:
    name: rabbitmq-server
    enabled: yes

- name: Restart RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: restarted
