---
# handlers file for osm_rabbitmq
- name: Restart RabbitMQ service
  systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

#- name: start RabbitMQ service
#  systemd:
#    name: rabbitmq-server
#    state: started
#    enabled: yes

- name: starting server
  ansible.builtin.systemd:
    name: rabbitmq-server.service 
    state: started
    enabled: yes

